[pytest]
markers =
    api: Pruebas de integración de Backend/API
    ui: Pruebas de interfaz de usuario de Selenium
    regression: Pruebas del set de regresión completo
    smoke: Pruebas críticas de humo

# Carpetas donde PyTest buscará pruebas automáticamente
testpaths = tests tests_api

# Configuración para activar y formatear los Logs en consola en tiempo real
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
